### ISSUE TITLE
Add new problems done in CPP

### ISSUE THREAD

**Issue by rishav142k** [rishav142k/OJ-problems#2]
Problems present on online judges such as Codechef, Codeforces, Leetcode, etc. are to be added here. Add any problem solutions in here.

**Comment by Uyadav207** [comment]
@rishav142k , assign this to me

**Comment by rishav142k** [comment]
> @rishav142k , assign this to me

Sure buddy, just make a PR with your code.

**Comment by rishav142k** [comment]
Anyone who wants to do this, just make a PR.

**Comment by rishav142k** [comment]
Add URL of the problem in the comment of the code.
