### ISSUE TITLE
Add CPP solutions

### ISSUE THREAD

**Issue by rishav142k** [rishav142k/OJ-problems#8]
Add CPP solutions in the already existing directory. 
Filename should be the same as Problem name and URL of the problem should be mentioned in the comment of the code.

**Comment by kratikasinghal** [comment]
hey! @rishav142k I would like to add some hackerrank problem codes

**Comment by rishav142k** [comment]
@kratikasinghal Sure. Just follow the guidelines and you are good to go!

**Comment by mgncodes** [comment]
Hi, can I add some Codeforces Problems? @rishav142k

**Comment by rishav142k** [comment]
@mgncodes Of course, man. There already are some codeforces problems in here. Make sure you abide by the rules mentioned in the first comment.
